var ARTICLE_SLUGS = {
  '1-9 day delay': '1-9-day-delay',
  '20hr delay': '20hr-delay',
  '21-Hour Marathon Talks End Without Deal — Vance Departs Pakistan Blaming Iran': '21-hour-marathon-talks-end-without-deal-vance-departs-pakistan-blaming-iran',
  '24hr delay': '24hr-delay',
  '3 day delay': '3-day-delay',
  'Abqaiq Facility Hit': 'abqaiq-facility-hit',
  'Angola': 'angola',
  'Arctic Drilling Debate': 'arctic-drilling-debate',
  'Australia': 'australia',
  'Azerbaijan': 'azerbaijan',
  'BP Accelerates Divestment of North Sea Assets': 'bp-accelerates-divestment-of-north-sea-assets',
  'BREAKING: Trump Announces Full Naval Blockade of Strait of Hormuz After Islamabad Talks Collapse': 'breaking-trump-announces-full-naval-blockade-of-strait-of-hormuz-after-islamabad',
  'Battery Storage Deployments Triple Year-Over-Year in the U.S.': 'battery-storage-deployments-triple-year-over-year-in-the-us',
  'Brazil': 'brazil',
  'Brazil\'s Pre-Salt Output Reaches 4 Million Barrels Per Day Milestone': 'brazils-pre-salt-output-reaches-4-million-barrels-per-day-milestone',
  'Brent Futures Open Interest Hits 3-Month High Ahead of OPEC Meeting': 'brent-futures-open-interest-hits-3-month-high-ahead-of-opec-meeting',
  'Brent-WTI Spread Widens to 4.44 on Atlantic Basin Tightness': 'brent-wti-spread-widens-to-444-on-atlantic-basin-tightness',
  'California Gas Prices Hit $5.18 as State-Specific Regulations Add Costs': 'california-gas-prices-hit-518-as-state-specific-regulations-add-costs',
  'Canada': 'canada',
  'Canadian Blends': 'canadian-blends',
  'Canadian Rig Count Rebounds to 118 as Spring Drilling Season Begins': 'canadian-rig-count-rebounds-to-118-as-spring-drilling-season-begins',
  'Carbon Capture Investment Reaches $12B Globally in 2025': 'carbon-capture-investment-reaches-12b-globally-in-2025',
  'Ceasefire Expires April 22 With No Extension in Sight': 'ceasefire-expires-april-22-with-no-extension-in-sight',
  'Ceasefire Largely Holding Day 2 — No New Gulf State Attacks Reported April 9': 'ceasefire-largely-holding-day-2-no-new-gulf-state-attacks-reported-april-9',
  'Cheapest Gas Prices by State Where to Find the Lowest Prices': 'cheapest-gas-prices-by-state-where-to-find-the-lowest-prices',
  'Chevron Completes Hess Merger, Gains Guyana Stabroek Stake': 'chevron-completes-hess-merger-gains-guyana-stabroek-stake',
  'China\'s Strategic Petroleum Reserve Purchases Slow in March': 'chinas-strategic-petroleum-reserve-purchases-slow-in-march',
  'Cold Snap Lifts Gas Prices': 'cold-snap-lifts-gas-prices',
  'ConocoPhillips Completes Marathon Oil Merger Integration': 'conocophillips-completes-marathon-oil-merger-integration',
  'Crude Braces for Turmoil': 'crude-braces-for-turmoil',
  'Crude Oil Crashes 15% as Strait of Hormuz Set to Reopen Under Ceasefire Terms': 'crude-oil-crashes-15-as-strait-of-hormuz-set-to-reopen-under-ceasefire-terms',
  'Crude Posts Historic Drop': 'crude-posts-historic-drop',
  'Daily Pricing': 'daily-pricing',
  'Daily pricing — 24hr delay': 'daily-pricing-24hr-delay',
  'Diesel and Heating Oil Margins Diverge as Trucking Demand Holds': 'diesel-and-heating-oil-margins-diverge-as-trucking-demand-holds',
  'Druzhba Pipeline': 'druzhba-pipeline',
  'Dubai Crude Fetches Premium as Asian Refiners Compete for Sour Barrels': 'dubai-crude-fetches-premium-as-asian-refiners-compete-for-sour-barrels',
  'EIA: U.S. Summer Gasoline Demand Expected to Average 9.1M BPD': 'eia-us-summer-gasoline-demand-expected-to-average-91m-bpd',
  'EU Carbon Price Stabilizes at €85/Tonne, Supporting Clean Energy Economics': 'eu-carbon-price-stabilizes-at-85tonne-supporting-clean-energy-economics',
  'Ecuador': 'ecuador',
  'Electric Vehicle Sales Growth Slows in Europe But Accelerates in Asia': 'electric-vehicle-sales-growth-slows-in-europe-but-accelerates-in-asia',
  'Equinor Wins New Offshore Wind Contracts in the North Sea': 'equinor-wins-new-offshore-wind-contracts-in-the-north-sea',
  'European Diesel Imports From Asia Rise as Arbitrage Window Opens': 'european-diesel-imports-from-asia-rise-as-arbitrage-window-opens',
  'European Energy Security Improves as LNG Import Capacity Doubles Since 2022': 'european-energy-security-improves-as-lng-import-capacity-doubles-since-2022',
  'European Natural Gas Prices Rally as Cold Snap Forecast Returns': 'european-natural-gas-prices-rally-as-cold-snap-forecast-returns',
  'European Refiners Boost Margins With Russian Crude Alternatives': 'european-refiners-boost-margins-with-russian-crude-alternatives',
  'European TTF Gas Rallies 12 Percent on Cold Weather Forecast': 'european-ttf-gas-rallies-12-percent-on-cold-weather-forecast',
  'European TTF Gas Rallies 12% on Extended Cold Weather Forecast': 'european-ttf-gas-rallies-12-on-extended-cold-weather-forecast',
  'ExxonMobil Announces $4.2B Expansion of Permian Basin Operations': 'exxonmobil-announces-42b-expansion-of-permian-basin-operations',
  'ExxonMobil Reports $9.2B Q1 Profit, Raises Dividend 4%': 'exxonmobil-reports-92b-q1-profit-raises-dividend-4',
  'ExxonMobil Reports 9.2 Billion Q1 Profit Raises Dividend': 'exxonmobil-reports-92-billion-q1-profit-raises-dividend',
  'ExxonMobil vs. Chevron: Battle for Permian Supremacy': 'exxonmobil-vs-chevron-battle-for-permian-supremacy',
  'Fragile Truce Holds': 'fragile-truce-holds',
  'France Commits €10B to Build Six New EPR2 Reactors by 2040': 'france-commits-10b-to-build-six-new-epr2-reactors-by-2040',
  'Futures & Indexes': 'futures-indexes',
  'Gas Prices Today U.S. National and State Averages April 2026': 'gas-prices-today-us-national-and-state-averages-april-2026',
  'Global Energy Crisis Deepens as Diplomatic Off-Ramp Narrows': 'global-energy-crisis-deepens-as-diplomatic-off-ramp-narrows',
  'Global Energy Demand Growth Slows to 1.2 Percent in 2026': 'global-energy-demand-growth-slows-to-12-percent-in-2026',
  'Global Energy Demand Growth Slows to 1.2% in 2026, IEA Reports': 'global-energy-demand-growth-slows-to-12-in-2026-iea-reports',
  'Global Oil Demand Growth Slows to 900K BPD in 2026, IEA Says': 'global-oil-demand-growth-slows-to-900k-bpd-in-2026-iea-says',
  'Global Oil Tanker Rates Spike on Red Sea Rerouting Congestion': 'global-oil-tanker-rates-spike-on-red-sea-rerouting-congestion',
  'Global Renewable Investment Hits $1.8 Trillion in 2025, IRENA Reports': 'global-renewable-investment-hits-18-trillion-in-2025-irena-reports',
  'Global Renewable Investment Hits 1.8 Trillion in 2025': 'global-renewable-investment-hits-18-trillion-in-2025',
  'Global Solar Installations Reach Record 420 GW in 2025': 'global-solar-installations-reach-record-420-gw-in-2025',
  'Goldman Sachs Raises Brent Crude Forecast to $82 by Year-End': 'goldman-sachs-raises-brent-crude-forecast-to-82-by-year-end',
  'Goldman Sachs Raises Brent Forecast to 82 by Year-End': 'goldman-sachs-raises-brent-forecast-to-82-by-year-end',
  'Green Hydrogen Costs Fall 40% Since 2022 as Electrolyzer Scale Grows': 'green-hydrogen-costs-fall-40-since-2022-as-electrolyzer-scale-grows',
  'Green Hydrogen Electrolyzer Orders Surge 300% in 2025': 'green-hydrogen-electrolyzer-orders-surge-300-in-2025',
  'Grid-Scale Battery Storage Hits 100 GW Global Milestone': 'grid-scale-battery-storage-hits-100-gw-global-milestone',
  'Gulf Coast Refinery Margins Improve as Crack Spreads Widen': 'gulf-coast-refinery-margins-improve-as-crack-spreads-widen',
  'Gulf Facilities Damaged': 'gulf-facilities-damaged',
  'Gulf States Report Intercepting Iranian Drones and Missiles Hours After Truce Announced': 'gulf-states-report-intercepting-iranian-drones-and-missiles-hours-after-truce-an',
  'Guyana Stabroek Block Delivers New 1.5 Billion Barrel Discovery': 'guyana-stabroek-block-delivers-new-15-billion-barrel-discovery',
  'Guyana\'s Stabroek Block Delivers New 1.5 Billion Barrel Discovery': 'guyanas-stabroek-block-delivers-new-15-billion-barrel-discovery',
  'Heating Oil Futures Ease as Winter Demand Season Winds Down': 'heating-oil-futures-ease-as-winter-demand-season-winds-down',
  'Henry Hub Falls Below 3.50 as U.S. Storage Surplus Persists': 'henry-hub-falls-below-350-as-us-storage-surplus-persists',
  'Hormuz Reopening Imminent': 'hormuz-reopening-imminent',
  'How OPEC Controls Oil Prices Simple Explanation': 'how-opec-controls-oil-prices-simple-explanation',
  'How U.S. Oil Inventories Move Crude Prices Weekly EIA Report Guide': 'how-us-oil-inventories-move-crude-prices-weekly-eia-report-guide',
  'IEA Warns of Potential Supply Shortfall in Late 2026': 'iea-warns-of-potential-supply-shortfall-in-late-2026',
  'India Diversifies Crude Imports Away From Middle East Dependence': 'india-diversifies-crude-imports-away-from-middle-east-dependence',
  'India\'s Energy Consumption Surpasses Japan for First Time': 'indias-energy-consumption-surpasses-japan-for-first-time',
  'India\'s Solar Tariffs Drop to Record Low $0.029/kWh in Rajasthan Auction': 'indias-solar-tariffs-drop-to-record-low-0029kwh-in-rajasthan-auction',
  'International Rig Count Stable at 958 as Middle East Activity Rises': 'international-rig-count-stable-at-958-as-middle-east-activity-rises',
  'Iran': 'iran',
  'Iran Blames U.S. for Failure of 21-Hour Islamabad Negotiations': 'iran-blames-us-for-failure-of-21-hour-islamabad-negotiations',
  'Iran Blames U.S. for Failure — Nuclear Program and Hormuz Control Key Sticking Points': 'iran-blames-us-for-failure-nuclear-program-and-hormuz-control-key-sticking-point',
  'Iran Ceasefire Rocks Markets': 'iran-ceasefire-rocks-markets',
  'Iran Nuclear Deal Stalls': 'iran-nuclear-deal-stalls',
  'Iran Nuclear Program Remains Central Sticking Point in U.S. Negotiations': 'iran-nuclear-program-remains-central-sticking-point-in-us-negotiations',
  'Iran Warns of Strong Responses if Israeli Lebanon Strikes Continue': 'iran-warns-of-strong-responses-if-israeli-lebanon-strikes-continue',
  'Iraq': 'iraq',
  'Iraq Struggles to Meet OPEC+ Production Quota Compliance': 'iraq-struggles-to-meet-opec-production-quota-compliance',
  'Islamabad Talks Collapse': 'islamabad-talks-collapse',
  'Islamabad Talks Collapse After 21-Hour Marathon — No Deal Reached Between U.S. and Iran': 'islamabad-talks-collapse-after-21-hour-marathon-no-deal-reached-between-us-and-i',
  'Islamabad Talks Friday': 'islamabad-talks-friday',
  'Israel Continues Lebanon Strikes Despite Ceasefire — Netanyahu Says Hezbollah Not Included': 'israel-continues-lebanon-strikes-despite-ceasefire-netanyahu-says-hezbollah-not-',
  'Israel Escalates in Beirut': 'israel-escalates-in-beirut',
  'Israel Struck 200+ Hezbollah Targets During Islamabad Peace Talks': 'israel-struck-200-hezbollah-targets-during-islamabad-peace-talks',
  'Israel-Lebanon Direct Negotiations Set for Tuesday in Washington': 'israel-lebanon-direct-negotiations-set-for-tuesday-in-washington',
  'Israel-Lebanon Direct Talks Set for Tuesday in Washington': 'israel-lebanon-direct-talks-set-for-tuesday-in-washington',
  'Israel-Lebanon Talks Tuesday': 'israel-lebanon-talks-tuesday',
  'Japan LNG Spot Price Drops to $12.40/MMBtu on Mild Asian Demand': 'japan-lng-spot-price-drops-to-1240mmbtu-on-mild-asian-demand',
  'Kazakhstan': 'kazakhstan',
  'Keystone Pipeline Restarts After Maintenance Shutdown': 'keystone-pipeline-restarts-after-maintenance-shutdown',
  'Kuwait Reports Significant Damage to Oil Facilities from Iranian Drone Attacks': 'kuwait-reports-significant-damage-to-oil-facilities-from-iranian-drone-attacks',
  'Managed Money Net Longs in Crude Futures Rise for Fourth Straight Week': 'managed-money-net-longs-in-crude-futures-rise-for-fourth-straight-week',
  'Markets React to Unexpected Inventory Build in Cushing Hub': 'markets-react-to-unexpected-inventory-build-in-cushing-hub',
  'Mexico': 'mexico',
  'Microsoft Signs 20-Year Nuclear Power Purchase Agreement for Data Centers': 'microsoft-signs-20-year-nuclear-power-purchase-agreement-for-data-centers',
  'Middle East Tensions Persist': 'middle-east-tensions-persist',
  'Natural Gas Flaring Reduction Efforts Gain Momentum in Permian': 'natural-gas-flaring-reduction-efforts-gain-momentum-in-permian',
  'Netanyahu Seeks Direct Lebanon Negotiations as Israel Continues Hezbollah Strikes': 'netanyahu-seeks-direct-lebanon-negotiations-as-israel-continues-hezbollah-strike',
  'New Deepwater Discovery Off Guyana Could Hold 1.5 Billion Barrels': 'new-deepwater-discovery-off-guyana-could-hold-15-billion-barrels',
  'Nigeria': 'nigeria',
  'Nigeria Pipeline Security Improves 40% Under New Government Program': 'nigeria-pipeline-security-improves-40-under-new-government-program',
  'Nigeria Security Improvements': 'nigeria-security-improvements',
  'Nigerian Pipeline Security Improves, Boosting Crude Output': 'nigerian-pipeline-security-improves-boosting-crude-output',
  'North Sea Forties Pipeline Restart Eases Brent Supply Concerns': 'north-sea-forties-pipeline-restart-eases-brent-supply-concerns',
  'Northeast Home Heating Costs Rose 8% This Winter vs. Last Year': 'northeast-home-heating-costs-rose-8-this-winter-vs-last-year',
  'NuScale Small Modular Reactor Receives Full NRC Certification': 'nuscale-small-modular-reactor-receives-full-nrc-certification',
  'NuScale Small Modular Reactor Receives Full NRC Design Certification': 'nuscale-small-modular-reactor-receives-full-nrc-design-certification',
  'Nuclear Issue Unresolved': 'nuclear-issue-unresolved',
  'Nuclear Renaissance: Small Modular Reactors Enter Commercial Phase': 'nuclear-renaissance-small-modular-reactors-enter-commercial-phase',
  'OPEC Basket Price Holds Above $74 Amid Production Cut Extensions': 'opec-basket-price-holds-above-74-amid-production-cut-extensions',
  'OPEC Members': 'opec-members',
  'OPEC Plus Production Cuts What They Mean for Oil Prices in 2026': 'opec-plus-production-cuts-what-they-mean-for-oil-prices-in-2026',
  'OPEC+ Compliance Reaches 116% as Iraq Over-Produces Again': 'opec-compliance-reaches-116-as-iraq-over-produces-again',
  'OPEC+ Considers Easing Production Cuts in Q4 2026': 'opec-considers-easing-production-cuts-in-q4-2026',
  'OPEC+ Emergency Response': 'opec-emergency-response',
  'OPEC+ Emergency Session Expected as Oil Prices Face Largest One-Day Drop Since 2020': 'opec-emergency-session-expected-as-oil-prices-face-largest-one-day-drop-since-20',
  'OPEC+ Holds Steady': 'opec-holds-steady',
  'OPEC+ Quota Compliance': 'opec-quota-compliance',
  'OPEC+ Signals Extended Production Cuts Through Q3 2026 Amid Demand Uncertainty': 'opec-signals-extended-production-cuts-through-q3-2026-amid-demand-uncertainty',
  'Offshore Wind Capacity Surpasses 80 GW Globally': 'offshore-wind-capacity-surpasses-80-gw-globally',
  'Offshore Wind Capacity Surpasses 80 GW Globally as Costs Stabilize': 'offshore-wind-capacity-surpasses-80-gw-globally-as-costs-stabilize',
  'Oil Markets Brace for Renewed Volatility as Ceasefire Future Uncertain': 'oil-markets-brace-for-renewed-volatility-as-ceasefire-future-uncertain',
  'Oil Markets Face Renewed Volatility as Islamabad Talks Fail': 'oil-markets-face-renewed-volatility-as-islamabad-talks-fail',
  'Oil Price Forecast 2026 What Analysts Predict for Crude': 'oil-price-forecast-2026-what-analysts-predict-for-crude',
  'Oil Prices Expected to Surge as Markets Open Monday — Analysts Warn of $110+ WTI': 'oil-prices-expected-to-surge-as-markets-open-monday-analysts-warn-of-110-wti',
  'Options Market Pricing Elevated Volatility Through Summer 2026': 'options-market-pricing-elevated-volatility-through-summer-2026',
  'Pakistan Urges Both Sides to Continue Diplomacy Despite Failed Talks': 'pakistan-urges-both-sides-to-continue-diplomacy-despite-failed-talks',
  'Pakistan Urges Continued Diplomacy After U.S.-Iran Talks End Without Deal': 'pakistan-urges-continued-diplomacy-after-us-iran-talks-end-without-deal',
  'Pakistan Urges Continued Diplomacy — Foreign Minister Says Ceasefire Must Hold': 'pakistan-urges-continued-diplomacy-foreign-minister-says-ceasefire-must-hold',
  'Permian Basin Output Hits Record 6.2M Barrels Per Day': 'permian-basin-output-hits-record-62m-barrels-per-day',
  'Permian Basin Production Hits Record 6.2 Million Barrels Per Day': 'permian-basin-production-hits-record-62-million-barrels-per-day',
  'Permian Basin Rigs Hold Steady at 302 Despite Overall U.S. Decline': 'permian-basin-rigs-hold-steady-at-302-despite-overall-us-decline',
  'Perovskite-Silicon Tandem Cells Hit 33.9% Efficiency Record': 'perovskite-silicon-tandem-cells-hit-339-efficiency-record',
  'Primary benchmarks — LIVE via API where marked, others 1-24hr delay': 'primary-benchmarks-live-via-api-where-marked-others-1-24hr-delay',
  'Pump Price Relief Ahead': 'pump-price-relief-ahead',
  'Qatar': 'qatar',
  'Red Sea & Houthi Attacks': 'red-sea-houthi-attacks',
  'Red Sea / Bab el-Mandeb': 'red-sea-bab-el-mandeb',
  'Red Sea Attacks Force 60 Percent of Tanker Traffic to Reroute': 'red-sea-attacks-force-60-percent-of-tanker-traffic-to-reroute',
  'Red Sea Attacks Force 60% of Tanker Traffic to Reroute Around Africa': 'red-sea-attacks-force-60-of-tanker-traffic-to-reroute-around-africa',
  'Red Sea Shipping Disruptions Continue to Impact Oil Transit Routes': 'red-sea-shipping-disruptions-continue-to-impact-oil-transit-routes',
  'Red Sea Shipping Disruptions Impact on Oil and Gas Prices': 'red-sea-shipping-disruptions-impact-on-oil-and-gas-prices',
  'Refinery Margins Under Pressure': 'refinery-margins-under-pressure',
  'Renewable Energy Investment Hits Record $1.8 Trillion Globally in 2025': 'renewable-energy-investment-hits-record-18-trillion-globally-in-2025',
  'Renewable Surge Continues': 'renewable-surge-continues',
  'Renewables Provided 35 Percent of Global Electricity in 2025': 'renewables-provided-35-percent-of-global-electricity-in-2025',
  'Renewables Provided 35% of Global Electricity in 2025, IEA Confirms': 'renewables-provided-35-of-global-electricity-in-2025-iea-confirms',
  'Russia': 'russia',
  'Russia Ukraine War Impact on Global Energy Markets 2026 Update': 'russia-ukraine-war-impact-on-global-energy-markets-2026-update',
  'Russia-Ukraine Energy War': 'russia-ukraine-energy-war',
  'Russian Oil Exports Shift Further Toward Asian Markets': 'russian-oil-exports-shift-further-toward-asian-markets',
  'Satellite Imagery Shows Smoke Rising from Saudi Aramco Abqaiq Facility': 'satellite-imagery-shows-smoke-rising-from-saudi-aramco-abqaiq-facility',
  'Saudi Arabia': 'saudi-arabia',
  'Saudi Arabia Holds Firm on April OSP Despite Market Pressure': 'saudi-arabia-holds-firm-on-april-osp-despite-market-pressure',
  'Saudi Aramco Invests $2B in South Korean Refinery Expansion': 'saudi-aramco-invests-2b-in-south-korean-refinery-expansion',
  'Saudi Aramco Invests $2B in South Korean Refining Complex': 'saudi-aramco-invests-2b-in-south-korean-refining-complex',
  'Saudi Aramco Restores East-West Pipeline Capacity After Drone Damage': 'saudi-aramco-restores-east-west-pipeline-capacity-after-drone-damage',
  'Saudi-Iran Détente': 'saudi-iran-dtente',
  'Saudi-Iran Détente Reduces Persian Gulf Risk Premium': 'saudi-iran-dtente-reduces-persian-gulf-risk-premium',
  'Shell Accelerates North Sea Asset Sales Worth $4.5B': 'shell-accelerates-north-sea-asset-sales-worth-45b',
  'Shell Accelerates North Sea Asset Sales Worth 4.5 Billion': 'shell-accelerates-north-sea-asset-sales-worth-45-billion',
  'Shell Reports Strong Q1 Upstream Earnings, Raises Dividend': 'shell-reports-strong-q1-upstream-earnings-raises-dividend',
  'Strait Still Blocked': 'strait-still-blocked',
  'Strait of Hormuz': 'strait-of-hormuz',
  'Strait of Hormuz Risk': 'strait-of-hormuz-risk',
  'Strait of Hormuz Still Not Meaningfully Reopened Despite Ceasefire Terms': 'strait-of-hormuz-still-not-meaningfully-reopened-despite-ceasefire-terms',
  'Strait of Hormuz Why This Chokepoint Controls Global Oil Prices': 'strait-of-hormuz-why-this-chokepoint-controls-global-oil-prices',
  'Strait of Hormuz: From Iranian Blockade to U.S. Naval Blockade': 'strait-of-hormuz-from-iranian-blockade-to-us-naval-blockade',
  'Strait of Malacca': 'strait-of-malacca',
  'Suez Canal': 'suez-canal',
  'Summer Gas Prices 2026 Forecast What to Expect at the Pump': 'summer-gas-prices-2026-forecast-what-to-expect-at-the-pump',
  'Texas Wind Generation Sets New Record at 35 GW During March Storm': 'texas-wind-generation-sets-new-record-at-35-gw-during-march-storm',
  'The New Oil Order: How OPEC+ Strategy Is Reshaping Global Crude Markets in 2026': 'the-new-oil-order-how-opec-strategy-is-reshaping-global-crude-markets-in-2026',
  'TotalEnergies Signs 20-Year LNG Supply Agreement with India': 'totalenergies-signs-20-year-lng-supply-agreement-with-india',
  'TotalEnergies Signs Major LNG Supply Deal with India': 'totalenergies-signs-major-lng-supply-deal-with-india',
  'Trump Announces Full Naval Blockade of Strait of Hormuz': 'trump-announces-full-naval-blockade-of-strait-of-hormuz',
  'Trump Announces Hormuz Blockade': 'trump-announces-hormuz-blockade',
  'Trump Orders Full Naval Blockade of Strait of Hormuz After Islamabad Talks Collapse': 'trump-orders-full-naval-blockade-of-strait-of-hormuz-after-islamabad-talks-colla',
  'Trump Says Iran Nuclear Enrichment Must End — Talks Set for Friday in Islamabad': 'trump-says-iran-nuclear-enrichment-must-end-talks-set-for-friday-in-islamabad',
  'Two-Week Ceasefire Expires April 22 — No Extension Path After Failed Talks': 'two-week-ceasefire-expires-april-22-no-extension-path-after-failed-talks',
  'Two-Week Ceasefire Expires April 22 — No Path to Extension Visible': 'two-week-ceasefire-expires-april-22-no-path-to-extension-visible',
  'Two-Week Truce Expires April 22': 'two-week-truce-expires-april-22',
  'U.S. Average Gas Price Rises to $3.42/Gallon Ahead of Spring Driving Season': 'us-average-gas-price-rises-to-342gallon-ahead-of-spring-driving-season',
  'U.S. Average Gas Price Rises to 3.42 Per Gallon': 'us-average-gas-price-rises-to-342-per-gallon',
  'U.S. Clean Energy Jobs Surpass 4 Million for First Time': 'us-clean-energy-jobs-surpass-4-million-for-first-time',
  'U.S. Diesel Prices Why Diesel Costs More Than Gasoline': 'us-diesel-prices-why-diesel-costs-more-than-gasoline',
  'U.S. Gas Prices Ease Slightly to $4.13 National Average as Ceasefire Holds': 'us-gas-prices-ease-slightly-to-413-national-average-as-ceasefire-holds',
  'U.S. Gas Prices Expected to Drop Sharply if Ceasefire Holds and Hormuz Reopens': 'us-gas-prices-expected-to-drop-sharply-if-ceasefire-holds-and-hormuz-reopens',
  'U.S. Gas Prices Expected to Ease if Ceasefire Holds — National Average $4.16': 'us-gas-prices-expected-to-ease-if-ceasefire-holds-national-average-416',
  'U.S. Gas Prices Hold at $4.13 National Average as Ceasefire Uncertainty Persists': 'us-gas-prices-hold-at-413-national-average-as-ceasefire-uncertainty-persists',
  'U.S. Gulf Coast LNG': 'us-gulf-coast-lng',
  'U.S. Inventories Draw Down': 'us-inventories-draw-down',
  'U.S. LNG Exports Hit Record 14 Bcf/d as Golden Pass Begins Operations': 'us-lng-exports-hit-record-14-bcfd-as-golden-pass-begins-operations',
  'U.S. Power Grid Faces Record Summer Demand From Data Center Expansion': 'us-power-grid-faces-record-summer-demand-from-data-center-expansion',
  'U.S. Power Grid Faces Record Summer Demand From Data Centers': 'us-power-grid-faces-record-summer-demand-from-data-centers',
  'U.S. Rig Count Falls for Third Consecutive Week, Baker Hughes Reports': 'us-rig-count-falls-for-third-consecutive-week-baker-hughes-reports',
  'U.S. Rig Count Falls to 584 Down 5 From Prior Week': 'us-rig-count-falls-to-584-down-5-from-prior-week',
  'U.S. Shale Operators Report Highest Well Productivity on Record': 'us-shale-operators-report-highest-well-productivity-on-record',
  'U.S. Tightens Sanctions Enforcement on Russian Oil Price Cap': 'us-tightens-sanctions-enforcement-on-russian-oil-price-cap',
  'U.S. Tightens Sanctions on Russian Oil Price Cap Violators': 'us-tightens-sanctions-on-russian-oil-price-cap-violators',
  'U.S. Utility-Scale Solar Pipeline Exceeds 300 GW as IRA Credits Flow': 'us-utility-scale-solar-pipeline-exceeds-300-gw-as-ira-credits-flow',
  'U.S.-China Trade Tensions': 'us-china-trade-tensions',
  'U.S.-Iran Ceasefire Takes Effect After Pakistan-Brokered Deal Halts 40 Days of Conflict': 'us-iran-ceasefire-takes-effect-after-pakistan-brokered-deal-halts-40-days-of-con',
  'UAE': 'uae',
  'United States — Oklahoma': 'united-states-oklahoma',
  'United States — Other States': 'united-states-other-states',
  'United States — Texas': 'united-states-texas',
  'Uranium Spot Price Surges to $92/lb as Utility Contracting Accelerates': 'uranium-spot-price-surges-to-92lb-as-utility-contracting-accelerates',
  'Vance Leads U.S. Delegation': 'vance-leads-us-delegation',
  'Vance-Led U.S. Delegation Heading to Pakistan for Saturday Talks with Iran': 'vance-led-us-delegation-heading-to-pakistan-for-saturday-talks-with-iran',
  'Venezuela Sanctions Relief Under Review After Election Delays': 'venezuela-sanctions-relief-under-review-after-election-delays',
  'Venezuela Sanctions Relief Under Review as Election Promises Stall': 'venezuela-sanctions-relief-under-review-as-election-promises-stall',
  'Venezuela Sanctions Review': 'venezuela-sanctions-review',
  'Vestas Unveils 17 MW Offshore Turbine, World\'s Most Powerful': 'vestas-unveils-17-mw-offshore-turbine-worlds-most-powerful',
  'Vineyard Wind Achieves Full 800 MW Output Off Massachusetts Coast': 'vineyard-wind-achieves-full-800-mw-output-off-massachusetts-coast',
  'WTI Crude Climbs Past $71 as U.S. Inventories Post Sharp Drawdown': 'wti-crude-climbs-past-71-as-us-inventories-post-sharp-drawdown',
  'WTI Crude Climbs Past 71 on U.S. Inventory Drawdown': 'wti-crude-climbs-past-71-on-us-inventory-drawdown',
  'WTI Crude Settles at $94.41 — Biggest Single-Day Drop Since April 2020': 'wti-crude-settles-at-9441-biggest-single-day-drop-since-april-2020',
  'WTI Crude Surges Past $71 on Tighter U.S. Inventory Data': 'wti-crude-surges-past-71-on-tighter-us-inventory-data',
  'WTI Futures Curve Flips to Backwardation Through December 2026': 'wti-futures-curve-flips-to-backwardation-through-december-2026',
  'WTI vs Brent Crude Oil Key Differences Explained': 'wti-vs-brent-crude-oil-key-differences-explained',
  'What Is Brent Crude Oil and Why Does It Matter': 'what-is-brent-crude-oil-and-why-does-it-matter',
  'What Is the Rig Count and Why Does It Matter for Oil Prices': 'what-is-the-rig-count-and-why-does-it-matter-for-oil-prices',
  'Why Are Gas Prices So High What Drives Pump Prices in 2026': 'why-are-gas-prices-so-high-what-drives-pump-prices-in-2026',
  'Why European Gas Storage Levels Matter More Than Ever': 'why-european-gas-storage-levels-matter-more-than-ever',
};
function articleUrl(title) {
  var slug = ARTICLE_SLUGS[title];
  if (!slug) slug = title.toLowerCase().replace(/[^a-z0-9\s-]/g,'').replace(/[\s]+/g,'-').replace(/-+/g,'-').substring(0,80);
  var inSub = window.location.pathname.includes('/category/') || window.location.pathname.includes('/authors/') || window.location.pathname.includes('/articles/');
  return (inSub ? '../' : '') + 'articles/' + slug + '.html';
}
