// Auto-generated article slug map — do not edit manually.
// Rebuild with: python3 scripts/rebuild_slug_map.py
const ARTICLE_SLUGS = {
  "10-Day Ceasefire Begins Thursday 5 P.M.": "10-day-ceasefire-begins-thursday-5-pm",
  "20,000 Vessels Stranded": "20000-vessels-stranded",
  "20,000 Vessels Stranded Globally as Hormuz Shipping Collapses Over 90%": "20000-vessels-stranded-globally-as-hormuz-shipping-collapses-over-90",
  "21-Hour Marathon Talks End Without Deal \u2014 Vance Departs Pakistan Blaming Iran": "21-hour-marathon-talks-end-without-deal-vance-departs-pakistan-blaming-iran",
  "AAA Gas Average Falls 7 Cents in First Weekly Decline of Conflict": "aaa-gas-average-falls-7-cents-in-first-weekly-decline-of-conflict",
  "AAA National Falls 7 Cents to $4.09": "aaa-national-falls-7-cents-to-409",
  "AAA National Gas Average Falls 7 Cents to $4.09 \u2014 First Decline in Weeks": "aaa-national-gas-average-falls-7-cents-to-409-first-decline-in-weeks",
  "Abqaiq Facility Hit": "abqaiq-facility-hit",
  "April 206K bpd Increase Proceeds": "april-206k-bpd-increase-proceeds",
  "Arctic Drilling Debate": "arctic-drilling-debate",
  "Army Chief in Tehran": "army-chief-in-tehran",
  "BP Accelerates Divestment of North Sea Assets": "bp-accelerates-divestment-of-north-sea-assets",
  "BREAKING: Trump Announces Full Naval Blockade of Strait of Hormuz After Islamabad Talks Collapse": "breaking-trump-announces-full-naval-blockade-of-strait-of-hormuz-after-islamabad",
  "Battery Storage Deployments Triple Year-Over-Year in the U.S.": "battery-storage-deployments-triple-year-over-year-in-the-us",
  "Brazil's Pre-Salt Output Reaches 4 Million Barrels Per Day Milestone": "brazils-pre-salt-output-reaches-4-million-barrels-per-day-milestone",
  "Brent Futures Open Interest Hits 3-Month High Ahead of OPEC Meeting": "brent-futures-open-interest-hits-3-month-high-ahead-of-opec-meeting",
  "Brent Rises 4% as Doubts Resurface Over Scope of Iran Deal": "brent-rises-4-as-doubts-resurface-over-scope-of-iran-deal",
  "Brent-WTI Spread Widens to 4.44 on Atlantic Basin Tightness": "brent-wti-spread-widens-to-444-on-atlantic-basin-tightness",
  "California Gas Prices Hit $5.18 as State-Specific Regulations Add Costs": "california-gas-prices-hit-518-as-state-specific-regulations-add-costs",
  "Canadian Blends": "canadian-blends",
  "Canadian Rig Count Plunges on Spring Breakup \u2014 135 Active Rigs": "canadian-rig-count-plunges-on-spring-breakup-135-active-rigs",
  "Canadian Rig Count Rebounds to 118 as Spring Drilling Season Begins": "canadian-rig-count-rebounds-to-118-as-spring-drilling-season-begins",
  "Carbon Capture Investment Reaches $12B Globally in 2025": "carbon-capture-investment-reaches-12b-globally-in-2025",
  "Ceasefire Expires April 21 \u2014 One Week Remaining With No Deal in Place": "ceasefire-expires-april-21-one-week-remaining-with-no-deal-in-place",
  "Ceasefire Expires April 22 With No Extension in Sight": "ceasefire-expires-april-22-with-no-extension-in-sight",
  "Ceasefire Largely Holding Day 2 \u2014 No New Gulf State Attacks Reported April 9": "ceasefire-largely-holding-day-2-no-new-gulf-state-attacks-reported-april-9",
  "Cheapest Gas Prices Right Now \u2014 State Rankings": "cheapest-gas-prices-right-now-state-rankings",
  "Cheapest Gas Prices by State Where to Find the Lowest Prices": "cheapest-gas-prices-by-state-where-to-find-the-lowest-prices",
  "Cheniere Energy Sees Q1 LNG Demand Surge Before Strait Reopens": "cheniere-energy-sees-q1-lng-demand-surge-before-strait-reopens",
  "Cheniere Energy Sees Renewed LNG Premium as Hormuz Closes Again": "cheniere-energy-sees-renewed-lng-premium-as-hormuz-closes-again",
  "Cheniere Sees Strong Q1 LNG Demand Amid Hormuz Disruption": "cheniere-sees-strong-q1-lng-demand-amid-hormuz-disruption",
  "Chevron Completes Hess Merger, Gains Guyana Stabroek Stake": "chevron-completes-hess-merger-gains-guyana-stabroek-stake",
  "Chevron-Hess Arbitration Ruling Expected in Coming Weeks": "chevron-hess-arbitration-ruling-expected-in-coming-weeks",
  "China's Strategic Petroleum Reserve Purchases Slow in March": "chinas-strategic-petroleum-reserve-purchases-slow-in-march",
  "Cold Snap Lifts Gas Prices": "cold-snap-lifts-gas-prices",
  "ConocoPhillips Completes Marathon Oil Integration Synergies": "conocophillips-completes-marathon-oil-integration-synergies",
  "ConocoPhillips Completes Marathon Oil Merger Integration": "conocophillips-completes-marathon-oil-merger-integration",
  "Container Ship Struck by Unknown Projectile Off Oman Coast": "container-ship-struck-by-unknown-projectile-off-oman-coast",
  "Crude Braces for Turmoil": "crude-braces-for-turmoil",
  "Crude Oil Crashes 15% as Strait of Hormuz Set to Reopen Under Ceasefire Terms": "crude-oil-crashes-15-as-strait-of-hormuz-set-to-reopen-under-ceasefire-terms",
  "Crude Posts Historic Drop": "crude-posts-historic-drop",
  "Daily pricing \u2014 24hr delay": "daily-pricing-24hr-delay",
  "Diesel and Heating Oil Margins Diverge as Trucking Demand Holds": "diesel-and-heating-oil-margins-diverge-as-trucking-demand-holds",
  "Druzhba Pipeline": "druzhba-pipeline",
  "Dubai Crude Fetches Premium as Asian Refiners Compete for Sour Barrels": "dubai-crude-fetches-premium-as-asian-refiners-compete-for-sour-barrels",
  "EIA Reports Second Consecutive Weekly Crude Draw, Cushing Stocks Below 5-Year Average": "eia-reports-second-consecutive-weekly-crude-draw-cushing-stocks-below-5-year-ave",
  "EIA: U.S. Summer Gasoline Demand Expected to Average 9.1M BPD": "eia-us-summer-gasoline-demand-expected-to-average-91m-bpd",
  "EU Carbon Price Stabilizes at \u20ac85/Tonne, Supporting Clean Energy Economics": "eu-carbon-price-stabilizes-at-85tonne-supporting-clean-energy-economics",
  "Electric Vehicle Sales Growth Slows in Europe But Accelerates in Asia": "electric-vehicle-sales-growth-slows-in-europe-but-accelerates-in-asia",
  "Energy Stocks Rebound as Hormuz Re-Closure Lifts Crude Prices": "energy-stocks-rebound-as-hormuz-re-closure-lifts-crude-prices",
  "Energy Stocks Tumble as Oil Crashes 11% on Hormuz Reopening": "energy-stocks-tumble-as-oil-crashes-11-on-hormuz-reopening",
  "Equinor Wins New Offshore Wind Contracts in the North Sea": "equinor-wins-new-offshore-wind-contracts-in-the-north-sea",
  "European Diesel Imports From Asia Rise as Arbitrage Window Opens": "european-diesel-imports-from-asia-rise-as-arbitrage-window-opens",
  "European Energy Security Improves as LNG Import Capacity Doubles Since 2022": "european-energy-security-improves-as-lng-import-capacity-doubles-since-2022",
  "European Natural Gas Prices Rally as Cold Snap Forecast Returns": "european-natural-gas-prices-rally-as-cold-snap-forecast-returns",
  "European Refiners Boost Margins With Russian Crude Alternatives": "european-refiners-boost-margins-with-russian-crude-alternatives",
  "European TTF Gas Rallies 12 Percent on Cold Weather Forecast": "european-ttf-gas-rallies-12-percent-on-cold-weather-forecast",
  "European TTF Gas Rallies 12% on Extended Cold Weather Forecast": "european-ttf-gas-rallies-12-on-extended-cold-weather-forecast",
  "ExxonMobil Announces $4.2B Expansion of Permian Basin Operations": "exxonmobil-announces-42b-expansion-of-permian-basin-operations",
  "ExxonMobil Q1 Earnings Expected to Benefit from Elevated Crude Prices": "exxonmobil-q1-earnings-expected-to-benefit-from-elevated-crude-prices",
  "ExxonMobil Reports $9.2B Q1 Profit, Raises Dividend 4%": "exxonmobil-reports-92b-q1-profit-raises-dividend-4",
  "ExxonMobil Reports 9.2 Billion Q1 Profit Raises Dividend": "exxonmobil-reports-92-billion-q1-profit-raises-dividend",
  "ExxonMobil Shares Off 5% as Crude Sell-Off Accelerates": "exxonmobil-shares-off-5-as-crude-sell-off-accelerates",
  "ExxonMobil vs. Chevron: Battle for Permian Supremacy": "exxonmobil-vs-chevron-battle-for-permian-supremacy",
  "Fragile Truce Holds": "fragile-truce-holds",
  "France Commits \u20ac10B to Build Six New EPR2 Reactors by 2040": "france-commits-10b-to-build-six-new-epr2-reactors-by-2040",
  "French UN Peacekeeper Killed in Lebanon Attack, Macron Blames Hezbollah": "french-un-peacekeeper-killed-in-lebanon-attack-macron-blames-hezbollah",
  "French UN Peacekeeper Killed in Lebanon, Macron Blames Hezbollah": "french-un-peacekeeper-killed-in-lebanon-macron-blames-hezbollah",
  "French UN Peacekeeper Killed on Day 2 of Ceasefire": "french-un-peacekeeper-killed-on-day-2-of-ceasefire",
  "Futures & Indexes": "futures-indexes",
  "Gas Prices Continue Slide to $4.058 \u2014 Seventh Straight Daily Decline": "gas-prices-continue-slide-to-4058-seventh-straight-daily-decline",
  "Gas Prices Continue Slide \u2014 AAA National Falls to $4.076": "gas-prices-continue-slide-aaa-national-falls-to-4076",
  "Gas Prices Fall to $4.058 \u2014 Seventh Consecutive Daily Decline": "gas-prices-fall-to-4058-seventh-consecutive-daily-decline",
  "Gas Prices Fall to $4.076 \u2014 Lowest Level Since Late March": "gas-prices-fall-to-4076-lowest-level-since-late-march",
  "Gas Prices Today U.S. National and State Averages April 2026": "gas-prices-today-us-national-and-state-averages-april-2026",
  "Gasoline Futures Up 3.1%, Cracks Widen": "gasoline-futures-up-31-cracks-widen",
  "Global Energy Crisis Deepens as Diplomatic Off-Ramp Narrows": "global-energy-crisis-deepens-as-diplomatic-off-ramp-narrows",
  "Global Energy Demand Growth Slows to 1.2 Percent in 2026": "global-energy-demand-growth-slows-to-12-percent-in-2026",
  "Global Energy Demand Growth Slows to 1.2% in 2026, IEA Reports": "global-energy-demand-growth-slows-to-12-in-2026-iea-reports",
  "Global Oil Demand Growth Slows to 900K BPD in 2026, IEA Says": "global-oil-demand-growth-slows-to-900k-bpd-in-2026-iea-says",
  "Global Oil Tanker Rates Spike on Red Sea Rerouting Congestion": "global-oil-tanker-rates-spike-on-red-sea-rerouting-congestion",
  "Global Renewable Investment Hits $1.8 Trillion in 2025, IRENA Reports": "global-renewable-investment-hits-18-trillion-in-2025-irena-reports",
  "Global Renewable Investment Hits 1.8 Trillion in 2025": "global-renewable-investment-hits-18-trillion-in-2025",
  "Global Solar Installations Reach Record 420 GW in 2025": "global-solar-installations-reach-record-420-gw-in-2025",
  "Goldman Sachs Raises Brent Crude Forecast to $82 by Year-End": "goldman-sachs-raises-brent-crude-forecast-to-82-by-year-end",
  "Goldman Sachs Raises Brent Forecast to 82 by Year-End": "goldman-sachs-raises-brent-forecast-to-82-by-year-end",
  "Green Hydrogen Costs Fall 40% Since 2022 as Electrolyzer Scale Grows": "green-hydrogen-costs-fall-40-since-2022-as-electrolyzer-scale-grows",
  "Green Hydrogen Electrolyzer Orders Surge 300% in 2025": "green-hydrogen-electrolyzer-orders-surge-300-in-2025",
  "Grid-Scale Battery Storage Hits 100 GW Global Milestone": "grid-scale-battery-storage-hits-100-gw-global-milestone",
  "Gulf Coast Refinery Margins Improve as Crack Spreads Widen": "gulf-coast-refinery-margins-improve-as-crack-spreads-widen",
  "Gulf Facilities Damaged": "gulf-facilities-damaged",
  "Gulf States Report Intercepting Iranian Drones and Missiles Hours After Truce Announced": "gulf-states-report-intercepting-iranian-drones-and-missiles-hours-after-truce-an",
  "Gulf of Mexico Rig Count Rises to 13 as Deepwater Investment Returns": "gulf-of-mexico-rig-count-rises-to-13-as-deepwater-investment-returns",
  "Guyana Stabroek Block Delivers New 1.5 Billion Barrel Discovery": "guyana-stabroek-block-delivers-new-15-billion-barrel-discovery",
  "Guyana's Stabroek Block Delivers New 1.5 Billion Barrel Discovery": "guyanas-stabroek-block-delivers-new-15-billion-barrel-discovery",
  "Heating Oil Futures Ease as Winter Demand Season Winds Down": "heating-oil-futures-ease-as-winter-demand-season-winds-down",
  "Henry Hub Falls Below 3.50 as U.S. Storage Surplus Persists": "henry-hub-falls-below-350-as-us-storage-surplus-persists",
  "Hormuz Closed Again: Iran Reverses Course as Trump Refuses to Lift Blockade": "hormuz-closed-again-iran-reverses-course-as-trump-refuses-to-lift-blockade",
  "Hormuz Reopening Imminent": "hormuz-reopening-imminent",
  "Hormuz Reopens: Iran Declares Strait Open as Oil Crashes 11%": "hormuz-reopens-iran-declares-strait-open-as-oil-crashes-11",
  "How Are Gas Prices Set? From Crude Oil to the Pump": "how-are-gas-prices-set-crude-oil-to-pump",
  "How OPEC Controls Oil Prices Simple Explanation": "how-opec-controls-oil-prices-simple-explanation",
  "How U.S. Oil Inventories Move Crude Prices Weekly EIA Report Guide": "how-us-oil-inventories-move-crude-prices-weekly-eia-report-guide",
  "IEA Warns of Potential Supply Shortfall in Late 2026": "iea-warns-of-potential-supply-shortfall-in-late-2026",
  "IRGC Gunboats Fire on Two Indian-Flagged Merchant Ships in Strait of Hormuz": "irgc-gunboats-fire-on-two-indian-flagged-merchant-ships-in-strait-of-hormuz",
  "India Diversifies Crude Imports Away From Middle East Dependence": "india-diversifies-crude-imports-away-from-middle-east-dependence",
  "India Summons Iranian Ambassador Over Attack on Indian Merchant Ships": "india-summons-iranian-ambassador-over-attack-on-indian-merchant-ships",
  "India Summons Iranian Ambassador Over Shooting of Indian Ships": "india-summons-iranian-ambassador-over-shooting-of-indian-ships",
  "India's Energy Consumption Surpasses Japan for First Time": "indias-energy-consumption-surpasses-japan-for-first-time",
  "India's Solar Tariffs Drop to Record Low $0.029/kWh in Rajasthan Auction": "indias-solar-tariffs-drop-to-record-low-0029kwh-in-rajasthan-auction",
  "International Rig Count Drops 54 in March as Middle East Conflict Disrupts Drilling": "international-rig-count-drops-54-in-march-as-middle-east-conflict-disrupts-drill",
  "International Rig Count Stable at 958 as Middle East Activity Rises": "international-rig-count-stable-at-958-as-middle-east-activity-rises",
  "Iran Armed Forces on Maximum Combat Alert Amid U.S. Blockade": "iran-armed-forces-on-maximum-combat-alert-amid-us-blockade",
  "Iran Blames U.S. for Failure of 21-Hour Islamabad Negotiations": "iran-blames-us-for-failure-of-21-hour-islamabad-negotiations",
  "Iran Blames U.S. for Failure \u2014 Nuclear Program and Hormuz Control Key Sticking Points": "iran-blames-us-for-failure-nuclear-program-and-hormuz-control-key-sticking-point",
  "Iran Ceasefire Rocks Markets": "iran-ceasefire-rocks-markets",
  "Iran Closes Strait of Hormuz Again in Response to U.S. Blockade": "iran-closes-strait-of-hormuz-again-in-response-to-us-blockade",
  "Iran Declares Strait of Hormuz Completely Open": "iran-declares-strait-of-hormuz-completely-open",
  "Iran Declares Strait of Hormuz Completely Open for Commercial Traffic": "iran-declares-strait-of-hormuz-completely-open-for-commercial-traffic",
  "Iran Nuclear Deal Stalls": "iran-nuclear-deal-stalls",
  "Iran Nuclear Program Remains Central Sticking Point in U.S. Negotiations": "iran-nuclear-program-remains-central-sticking-point-in-us-negotiations",
  "Iran Re-Closes Strait of Hormuz After One-Day Reopening": "iran-re-closes-strait-of-hormuz-after-one-day-reopening",
  "Iran Rebuilding Bases": "iran-rebuilding-bases",
  "Iran Threatens to Block Red Sea and Gulf of Oman if U.S. Blockade Continues": "iran-threatens-to-block-red-sea-and-gulf-of-oman-if-us-blockade-continues",
  "Iran Warns of Strong Responses if Israeli Lebanon Strikes Continue": "iran-warns-of-strong-responses-if-israeli-lebanon-strikes-continue",
  "Iraq Struggles to Meet OPEC+ Production Quota Compliance": "iraq-struggles-to-meet-opec-production-quota-compliance",
  "Islamabad Talks Collapse": "islamabad-talks-collapse",
  "Islamabad Talks Collapse After 21-Hour Marathon \u2014 No Deal Reached Between U.S. and Iran": "islamabad-talks-collapse-after-21-hour-marathon-no-deal-reached-between-us-and-i",
  "Islamabad Talks Friday": "islamabad-talks-friday",
  "Israel Continues Lebanon Strikes Despite Ceasefire \u2014 Netanyahu Says Hezbollah Not Included": "israel-continues-lebanon-strikes-despite-ceasefire-netanyahu-says-hezbollah-not-",
  "Israel Escalates in Beirut": "israel-escalates-in-beirut",
  "Israel Struck 200+ Hezbollah Targets During Islamabad Peace Talks": "israel-struck-200-hezbollah-targets-during-islamabad-peace-talks",
  "Israel and Lebanon Begin 10-Day Ceasefire at 5 P.M. Thursday": "israel-and-lebanon-begin-10-day-ceasefire-at-5-pm-thursday",
  "Israel and Lebanon Begin 10-Day Ceasefire at 5 P.M. Thursday, Trump Announces": "israel-and-lebanon-begin-10-day-ceasefire-at-5-pm-thursday-trump-announces",
  "Israel-Lebanon 10-Day Ceasefire Takes Effect, Hezbollah Holds Fire": "israel-lebanon-10-day-ceasefire-takes-effect-hezbollah-holds-fire",
  "Israel-Lebanon Ceasefire Holds on First Full Day": "israel-lebanon-ceasefire-holds-on-first-full-day",
  "Israel-Lebanon Ceasefire Takes Effect as Hormuz Remains Closed": "israel-lebanon-ceasefire-takes-effect-as-hormuz-remains-closed",
  "Israel-Lebanon Ceasefire Takes Effect as US Blockade Continues": "israel-lebanon-ceasefire-takes-effect-as-us-blockade-continues",
  "Israel-Lebanon Direct Negotiations Set for Tuesday in Washington": "israel-lebanon-direct-negotiations-set-for-tuesday-in-washington",
  "Israel-Lebanon Direct Talks Set for Tuesday in Washington": "israel-lebanon-direct-talks-set-for-tuesday-in-washington",
  "Israel-Lebanon Progress": "israel-lebanon-progress",
  "Israel-Lebanon Talks Begin in Washington as Hezbollah Rejects Negotiations": "israel-lebanon-talks-begin-in-washington-as-hezbollah-rejects-negotiations",
  "Israel-Lebanon Talks Conclude \u2014 Further Negotiations Agreed at Mutually Set Venue": "israel-lebanon-talks-conclude-further-negotiations-agreed-at-mutually-set-venue",
  "Israel-Lebanon Talks Today": "israel-lebanon-talks-today",
  "Israel-Lebanon Talks Tuesday": "israel-lebanon-talks-tuesday",
  "Japan LNG Spot Price Drops to $12.40/MMBtu on Mild Asian Demand": "japan-lng-spot-price-drops-to-1240mmbtu-on-mild-asian-demand",
  "Keystone Pipeline Restarts After Maintenance Shutdown": "keystone-pipeline-restarts-after-maintenance-shutdown",
  "Kuwait Reports Significant Damage to Oil Facilities from Iranian Drone Attacks": "kuwait-reports-significant-damage-to-oil-facilities-from-iranian-drone-attacks",
  "Maersk, Hapag-Lloyd Suspend Hormuz Transits Again After Iran Reversal": "maersk-hapag-lloyd-suspend-hormuz-transits-again-after-iran-reversal",
  "Managed Money Net Longs in Crude Futures Rise for Fourth Straight Week": "managed-money-net-longs-in-crude-futures-rise-for-fourth-straight-week",
  "Markets React to Unexpected Inventory Build in Cushing Hub": "markets-react-to-unexpected-inventory-build-in-cushing-hub",
  "Microsoft Signs 20-Year Nuclear Power Purchase Agreement for Data Centers": "microsoft-signs-20-year-nuclear-power-purchase-agreement-for-data-centers",
  "Middle East Tensions Persist": "middle-east-tensions-persist",
  "Natural Gas Flaring Reduction Efforts Gain Momentum in Permian": "natural-gas-flaring-reduction-efforts-gain-momentum-in-permian",
  "Netanyahu Seeks Direct Lebanon Negotiations as Israel Continues Hezbollah Strikes": "netanyahu-seeks-direct-lebanon-negotiations-as-israel-continues-hezbollah-strike",
  "New Deepwater Discovery Off Guyana Could Hold 1.5 Billion Barrels": "new-deepwater-discovery-off-guyana-could-hold-15-billion-barrels",
  "Nigeria Pipeline Security Improves 40% Under New Government Program": "nigeria-pipeline-security-improves-40-under-new-government-program",
  "Nigeria Security Improvements": "nigeria-security-improvements",
  "Nigerian Pipeline Security Improves, Boosting Crude Output": "nigerian-pipeline-security-improves-boosting-crude-output",
  "North Sea Forties Pipeline Restart Eases Brent Supply Concerns": "north-sea-forties-pipeline-restart-eases-brent-supply-concerns",
  "Northeast Home Heating Costs Rose 8% This Winter vs. Last Year": "northeast-home-heating-costs-rose-8-this-winter-vs-last-year",
  "NuScale Small Modular Reactor Receives Full NRC Certification": "nuscale-small-modular-reactor-receives-full-nrc-certification",
  "NuScale Small Modular Reactor Receives Full NRC Design Certification": "nuscale-small-modular-reactor-receives-full-nrc-design-certification",
  "Nuclear Issue Unresolved": "nuclear-issue-unresolved",
  "Nuclear Renaissance: Small Modular Reactors Enter Commercial Phase": "nuclear-renaissance-small-modular-reactors-enter-commercial-phase",
  "OPEC Basket Price Holds Above $74 Amid Production Cut Extensions": "opec-basket-price-holds-above-74-amid-production-cut-extensions",
  "OPEC Plus Production Cuts What They Mean for Oil Prices in 2026": "opec-plus-production-cuts-what-they-mean-for-oil-prices-in-2026",
  "OPEC+ April Output Increase on Track": "opec-april-output-increase-on-track",
  "OPEC+ Compliance Reaches 116% as Iraq Over-Produces Again": "opec-compliance-reaches-116-as-iraq-over-produces-again",
  "OPEC+ Considers Easing Production Cuts in Q4 2026": "opec-considers-easing-production-cuts-in-q4-2026",
  "OPEC+ Emergency Response": "opec-emergency-response",
  "OPEC+ Emergency Session Expected as Oil Prices Face Largest One-Day Drop Since 2020": "opec-emergency-session-expected-as-oil-prices-face-largest-one-day-drop-since-20",
  "OPEC+ Holds Steady": "opec-holds-steady",
  "OPEC+ Proceeds with April Output Increase Despite Conflict": "opec-proceeds-with-april-output-increase-despite-conflict",
  "OPEC+ Quota Compliance": "opec-quota-compliance",
  "OPEC+ Signals Extended Production Cuts Through Q3 2026 Amid Demand Uncertainty": "opec-signals-extended-production-cuts-through-q3-2026-amid-demand-uncertainty",
  "OPEC+ Unchanged Despite Hormuz Re-Closure": "opec-unchanged-despite-hormuz-re-closure",
  "Offshore Wind Capacity Surpasses 80 GW Globally": "offshore-wind-capacity-surpasses-80-gw-globally",
  "Offshore Wind Capacity Surpasses 80 GW Globally as Costs Stabilize": "offshore-wind-capacity-surpasses-80-gw-globally-as-costs-stabilize",
  "Oil Futures vs Spot Prices: What's the Difference?": "oil-futures-vs-spot-prices-difference",
  "Oil Markets Brace for Renewed Volatility as Ceasefire Future Uncertain": "oil-markets-brace-for-renewed-volatility-as-ceasefire-future-uncertain",
  "Oil Markets Face Renewed Volatility as Islamabad Talks Fail": "oil-markets-face-renewed-volatility-as-islamabad-talks-fail",
  "Oil Plunges 11% as Hormuz Reopens \u2014 WTI Closes at $83.85": "oil-plunges-11-as-hormuz-reopens-wti-closes-at-8385",
  "Oil Plunges Most Since April 2020 on Hormuz Reopening News": "oil-plunges-most-since-april-2020-on-hormuz-reopening-news",
  "Oil Price Forecast 2026 What Analysts Predict for Crude": "oil-price-forecast-2026-what-analysts-predict-for-crude",
  "Oil Prices Climb Near $100 as Energy Secretary Warns Prices Will Keep Rising": "oil-prices-climb-near-100-as-energy-secretary-warns-prices-will-keep-rising",
  "Oil Prices Ease on Ceasefire Extension Hopes \u2014 WTI Pulls Back Below $95": "oil-prices-ease-on-ceasefire-extension-hopes-wti-pulls-back-below-95",
  "Oil Prices Expected to Surge as Markets Open Monday \u2014 Analysts Warn of $110+ WTI": "oil-prices-expected-to-surge-as-markets-open-monday-analysts-warn-of-110-wti",
  "Oil Prices Whipsaw on Hormuz Reversal \u2014 WTI Recovers From Friday\u2019s 11% Plunge": "oil-prices-whipsaw-on-hormuz-reversal-wti-recovers-from-fridays-11-plunge",
  "Options Market Pricing Elevated Volatility Through Summer 2026": "options-market-pricing-elevated-volatility-through-summer-2026",
  "Pakistan Army Chief Holds Emergency Talks in Tehran to Restart Negotiations": "pakistan-army-chief-holds-emergency-talks-in-tehran-to-restart-negotiations",
  "Pakistan FM Dar Working to Bridge U.S.-Iran Differences Before Tuesday Ceasefire Expiration": "pakistan-fm-dar-working-to-bridge-us-iran-differences-before-tuesday-ceasefire-e",
  "Pakistan Mediating Second Round of Talks": "pakistan-mediating-second-round-of-talks",
  "Pakistan Mediation Effort Intensifies Ahead of April 22 Deadline": "pakistan-mediation-effort-intensifies-ahead-of-april-22-deadline",
  "Pakistan PM Sharif Tours Qatar, Turkey in Mediation Effort": "pakistan-pm-sharif-tours-qatar-turkey-in-mediation-effort",
  "Pakistan PM Sharif Visits Qatar, Turkey in Continued U.S.-Iran Mediation Effort": "pakistan-pm-sharif-visits-qatar-turkey-in-continued-us-iran-mediation-effort",
  "Pakistan Urges Both Sides to Continue Diplomacy Despite Failed Talks": "pakistan-urges-both-sides-to-continue-diplomacy-despite-failed-talks",
  "Pakistan Urges Continued Diplomacy After U.S.-Iran Talks End Without Deal": "pakistan-urges-continued-diplomacy-after-us-iran-talks-end-without-deal",
  "Pakistan Urges Continued Diplomacy \u2014 Foreign Minister Says Ceasefire Must Hold": "pakistan-urges-continued-diplomacy-foreign-minister-says-ceasefire-must-hold",
  "Paris Summit Convenes Coalition on Hormuz Security": "paris-summit-convenes-coalition-on-hormuz-security",
  "Paris Summit Convenes Coalition on Hormuz Security and Shipping": "paris-summit-convenes-coalition-on-hormuz-security-and-shipping",
  "Paris Summit: Macron and Starmer Host Coalition on Hormuz Security": "paris-summit-macron-and-starmer-host-coalition-on-hormuz-security",
  "Permian Basin Operators Slow Drilling Amid Capital Discipline Push": "permian-basin-operators-slow-drilling-amid-capital-discipline-push",
  "Permian Basin Output Hits Record 6.2M Barrels Per Day": "permian-basin-output-hits-record-62m-barrels-per-day",
  "Permian Basin Production Hits Record 6.2 Million Barrels Per Day": "permian-basin-production-hits-record-62-million-barrels-per-day",
  "Permian Basin Rigs Hold Steady at 302 Despite Overall U.S. Decline": "permian-basin-rigs-hold-steady-at-302-despite-overall-us-decline",
  "Perovskite-Silicon Tandem Cells Hit 33.9% Efficiency Record": "perovskite-silicon-tandem-cells-hit-339-efficiency-record",
  "Primary benchmarks \u2014 LIVE via API where marked, others 1-24hr delay": "primary-benchmarks-live-via-api-where-marked-others-1-24hr-delay",
  "Pump Price Relief Ahead": "pump-price-relief-ahead",
  "Red Sea & Houthi Attacks": "red-sea-houthi-attacks",
  "Red Sea / Bab el-Mandeb": "red-sea-bab-el-mandeb",
  "Red Sea Attacks Force 60 Percent of Tanker Traffic to Reroute": "red-sea-attacks-force-60-percent-of-tanker-traffic-to-reroute",
  "Red Sea Attacks Force 60% of Tanker Traffic to Reroute Around Africa": "red-sea-attacks-force-60-of-tanker-traffic-to-reroute-around-africa",
  "Red Sea Shipping Disruptions Continue to Impact Oil Transit Routes": "red-sea-shipping-disruptions-continue-to-impact-oil-transit-routes",
  "Red Sea Shipping Disruptions Impact on Oil and Gas Prices": "red-sea-shipping-disruptions-impact-on-oil-and-gas-prices",
  "Refinery Margins Under Pressure": "refinery-margins-under-pressure",
  "Renewable Energy Investment Hits Record $1.8 Trillion Globally in 2025": "renewable-energy-investment-hits-record-18-trillion-globally-in-2025",
  "Renewable Surge Continues": "renewable-surge-continues",
  "Renewables Provided 35 Percent of Global Electricity in 2025": "renewables-provided-35-percent-of-global-electricity-in-2025",
  "Renewables Provided 35% of Global Electricity in 2025, IEA Confirms": "renewables-provided-35-of-global-electricity-in-2025-iea-confirms",
  "Russia Ukraine War Impact on Global Energy Markets 2026 Update": "russia-ukraine-war-impact-on-global-energy-markets-2026-update",
  "Russia-Ukraine Energy War": "russia-ukraine-energy-war",
  "Russian Oil Exports Continue Redirect to Asian Markets": "russian-oil-exports-continue-redirect-to-asian-markets",
  "Russian Oil Exports Shift Further Toward Asian Markets": "russian-oil-exports-shift-further-toward-asian-markets",
  "S&P 500 and Nasdaq Hit Record Highs as Oil Crashes": "sp-500-and-nasdaq-hit-record-highs-as-oil-crashes",
  "Satellite Imagery Shows Smoke Rising from Saudi Aramco Abqaiq Facility": "satellite-imagery-shows-smoke-rising-from-saudi-aramco-abqaiq-facility",
  "Satellite Images Show Iran Rebuilding Underground Missile Bases During Ceasefire": "satellite-images-show-iran-rebuilding-underground-missile-bases-during-ceasefire",
  "Saudi Arabia Holds Firm on April OSP Despite Market Pressure": "saudi-arabia-holds-firm-on-april-osp-despite-market-pressure",
  "Saudi Aramco Activates East-West Pipeline Contingency Protocols": "saudi-aramco-activates-east-west-pipeline-contingency-protocols",
  "Saudi Aramco Invests $2B in South Korean Refinery Expansion": "saudi-aramco-invests-2b-in-south-korean-refinery-expansion",
  "Saudi Aramco Invests $2B in South Korean Refining Complex": "saudi-aramco-invests-2b-in-south-korean-refining-complex",
  "Saudi Aramco Restores East-West Pipeline Capacity After Drone Damage": "saudi-aramco-restores-east-west-pipeline-capacity-after-drone-damage",
  "Saudi Aramco Restores East-West Pipeline Full Capacity": "saudi-aramco-restores-east-west-pipeline-full-capacity",
  "Saudi-Iran D\u00e9tente": "saudi-iran-dtente",
  "Saudi-Iran D\u00e9tente Reduces Persian Gulf Risk Premium": "saudi-iran-dtente-reduces-persian-gulf-risk-premium",
  "Second Round Discussed": "second-round-discussed",
  "Second Round of US-Iran Talks Expected This Weekend": "second-round-of-us-iran-talks-expected-this-weekend",
  "Shell Accelerates North Sea Asset Sales Worth $4.5B": "shell-accelerates-north-sea-asset-sales-worth-45b",
  "Shell Accelerates North Sea Asset Sales Worth 4.5 Billion": "shell-accelerates-north-sea-asset-sales-worth-45-billion",
  "Shell Reports Higher Q1 Upstream Earnings, Maintains Dividend": "shell-reports-higher-q1-upstream-earnings-maintains-dividend",
  "Shell Reports Strong Q1 Upstream Earnings, Raises Dividend": "shell-reports-strong-q1-upstream-earnings-raises-dividend",
  "Strait Still Blocked": "strait-still-blocked",
  "Strait of Hormuz": "strait-of-hormuz",
  "Strait of Hormuz Remains Closed Despite Ceasefire Framework": "strait-of-hormuz-remains-closed-despite-ceasefire-framework",
  "Strait of Hormuz Remains Closed to Most Commercial Traffic Despite Ceasefire": "strait-of-hormuz-remains-closed-to-most-commercial-traffic-despite-ceasefire",
  "Strait of Hormuz Risk": "strait-of-hormuz-risk",
  "Strait of Hormuz Still Not Meaningfully Reopened Despite Ceasefire Terms": "strait-of-hormuz-still-not-meaningfully-reopened-despite-ceasefire-terms",
  "Strait of Hormuz Why This Chokepoint Controls Global Oil Prices": "strait-of-hormuz-why-this-chokepoint-controls-global-oil-prices",
  "Strait of Hormuz: From Iranian Blockade to U.S. Naval Blockade": "strait-of-hormuz-from-iranian-blockade-to-us-naval-blockade",
  "Strait of Malacca": "strait-of-malacca",
  "Summer Gas Prices 2026 Forecast What to Expect at the Pump": "summer-gas-prices-2026-forecast-what-to-expect-at-the-pump",
  "Surprise 9.13 Million Barrel Crude Draw Sends WTI Above $94": "surprise-913-million-barrel-crude-draw-sends-wti-above-94",
  "Texas Wind Generation Sets New Record at 35 GW During March Storm": "texas-wind-generation-sets-new-record-at-35-gw-during-march-storm",
  "The New Oil Order: How OPEC+ Strategy Is Reshaping Global Crude Markets in 2026": "the-new-oil-order-how-opec-strategy-is-reshaping-global-crude-markets-in-2026",
  "TotalEnergies Signs 20-Year LNG Supply Agreement with India": "totalenergies-signs-20-year-lng-supply-agreement-with-india",
  "TotalEnergies Signs Major LNG Supply Deal with India": "totalenergies-signs-major-lng-supply-deal-with-india",
  "Trump Announces Full Naval Blockade of Strait of Hormuz": "trump-announces-full-naval-blockade-of-strait-of-hormuz",
  "Trump Announces Hormuz Blockade": "trump-announces-hormuz-blockade",
  "Trump Orders Full Naval Blockade of Strait of Hormuz After Islamabad Talks Collapse": "trump-orders-full-naval-blockade-of-strait-of-hormuz-after-islamabad-talks-colla",
  "Trump Says Iran Nuclear Enrichment Must End \u2014 Talks Set for Friday in Islamabad": "trump-says-iran-nuclear-enrichment-must-end-talks-set-for-friday-in-islamabad",
  "Trump Says New Iran Talks Could Happen in Next Two Days \u2014 Second Islamabad Round Discussed": "trump-says-new-iran-talks-could-happen-in-next-two-days-second-islamabad-round-d",
  "Trump Says U.S. 'Very Close' to Deal with Iran": "trump-says-us-very-close-to-deal-with-iran",
  "Trump Says U.S. 'Very Close' to Deal with Iran as Ceasefire Nears April 22 Expiration": "trump-says-us-very-close-to-deal-with-iran-as-ceasefire-nears-april-22-expiratio",
  "Trump Says US Blockade of Iranian Ports Will Remain in Full Force Until Peace Deal": "trump-says-us-blockade-of-iranian-ports-will-remain-in-full-force-until-peace-de",
  "Trump Threatens to Resume Bombing if No Deal by Tuesday": "trump-threatens-to-resume-bombing-if-no-deal-by-tuesday",
  "Trump Warns He May Not Extend Ceasefire, Threatens to Resume Bombing": "trump-warns-he-may-not-extend-ceasefire-threatens-to-resume-bombing",
  "Trump Warns He May Not Extend Ceasefire, Threatens to Resume Bombing Iran": "trump-warns-he-may-not-extend-ceasefire-threatens-to-resume-bombing-iran",
  "Trump: Blockade Continues Until Peace Deal Signed": "trump-blockade-continues-until-peace-deal-signed",
  "Two-Week Ceasefire Expires April 22 \u2014 No Extension Path After Failed Talks": "two-week-ceasefire-expires-april-22-no-extension-path-after-failed-talks",
  "Two-Week Ceasefire Expires April 22 \u2014 No Path to Extension Visible": "two-week-ceasefire-expires-april-22-no-path-to-extension-visible",
  "Two-Week Extension Discussed": "two-week-extension-discussed",
  "Two-Week Extension Under Discussion": "two-week-extension-under-discussion",
  "Two-Week Truce Expires April 22": "two-week-truce-expires-april-22",
  "U.S. Average Gas Price Rises to $3.42/Gallon Ahead of Spring Driving Season": "us-average-gas-price-rises-to-342gallon-ahead-of-spring-driving-season",
  "U.S. Average Gas Price Rises to 3.42 Per Gallon": "us-average-gas-price-rises-to-342-per-gallon",
  "U.S. Clean Energy Jobs Surpass 4 Million for First Time": "us-clean-energy-jobs-surpass-4-million-for-first-time",
  "U.S. Diesel Prices Why Diesel Costs More Than Gasoline": "us-diesel-prices-why-diesel-costs-more-than-gasoline",
  "U.S. Gas Prices Drop to $4.11 National Average as Crude Stabilizes": "us-gas-prices-drop-to-411-national-average-as-crude-stabilizes",
  "U.S. Gas Prices Ease Slightly to $4.13 National Average as Ceasefire Holds": "us-gas-prices-ease-slightly-to-413-national-average-as-ceasefire-holds",
  "U.S. Gas Prices Expected to Drop Sharply if Ceasefire Holds and Hormuz Reopens": "us-gas-prices-expected-to-drop-sharply-if-ceasefire-holds-and-hormuz-reopens",
  "U.S. Gas Prices Expected to Ease if Ceasefire Holds \u2014 National Average $4.16": "us-gas-prices-expected-to-ease-if-ceasefire-holds-national-average-416",
  "U.S. Gas Prices Hold at $4.13 National Average as Ceasefire Uncertainty Persists": "us-gas-prices-hold-at-413-national-average-as-ceasefire-uncertainty-persists",
  "U.S. Gulf Coast LNG": "us-gulf-coast-lng",
  "U.S. Inventories Draw Down": "us-inventories-draw-down",
  "U.S. LNG Exports Hit Record 14 Bcf/d as Golden Pass Begins Operations": "us-lng-exports-hit-record-14-bcfd-as-golden-pass-begins-operations",
  "U.S. Naval Blockade Now in Effect \u2014 Iran Accuses Washington of Piracy": "us-naval-blockade-now-in-effect-iran-accuses-washington-of-piracy",
  "U.S. Power Grid Faces Record Summer Demand From Data Center Expansion": "us-power-grid-faces-record-summer-demand-from-data-center-expansion",
  "U.S. Power Grid Faces Record Summer Demand From Data Centers": "us-power-grid-faces-record-summer-demand-from-data-centers",
  "U.S. Rig Count Falls 3 to 545 \u2014 Oil Rigs Steady, Gas Rigs Decline": "us-rig-count-falls-3-to-545-oil-rigs-steady-gas-rigs-decline",
  "U.S. Rig Count Falls for Third Consecutive Week, Baker Hughes Reports": "us-rig-count-falls-for-third-consecutive-week-baker-hughes-reports",
  "U.S. Rig Count Falls to 584 Down 5 From Prior Week": "us-rig-count-falls-to-584-down-5-from-prior-week",
  "U.S. Shale Operators Report Highest Well Productivity on Record": "us-shale-operators-report-highest-well-productivity-on-record",
  "U.S. Tightens Sanctions Enforcement on Russian Oil Price Cap": "us-tightens-sanctions-enforcement-on-russian-oil-price-cap",
  "U.S. Tightens Sanctions on Russian Oil Price Cap Violators": "us-tightens-sanctions-on-russian-oil-price-cap-violators",
  "U.S. Utility-Scale Solar Pipeline Exceeds 300 GW as IRA Credits Flow": "us-utility-scale-solar-pipeline-exceeds-300-gw-as-ira-credits-flow",
  "U.S. and Iran Considering Two-Week Ceasefire Extension \u2014 Bloomberg Reports": "us-and-iran-considering-two-week-ceasefire-extension-bloomberg-reports",
  "U.S.-China Trade Tensions": "us-china-trade-tensions",
  "U.S.-Iran Ceasefire Explained: Timeline, Terms, and Expiration": "us-iran-ceasefire-explained-timeline-terms-expiration",
  "U.S.-Iran Ceasefire Takes Effect After Pakistan-Brokered Deal Halts 40 Days of Conflict": "us-iran-ceasefire-takes-effect-after-pakistan-brokered-deal-halts-40-days-of-con",
  "United States \u2014 Oklahoma": "united-states-oklahoma",
  "United States \u2014 Other States": "united-states-other-states",
  "United States \u2014 Texas": "united-states-texas",
  "Uranium Enrichment Timeframe Emerges as Key Sticking Point in Peace Talks": "uranium-enrichment-timeframe-emerges-as-key-sticking-point-in-peace-talks",
  "Uranium Spot Price Surges to $92/lb as Utility Contracting Accelerates": "uranium-spot-price-surges-to-92lb-as-utility-contracting-accelerates",
  "Vance Expected to Lead Second Round of Iran Negotiations if Talks Resume": "vance-expected-to-lead-second-round-of-iran-negotiations-if-talks-resume",
  "Vance Leads U.S. Delegation": "vance-leads-us-delegation",
  "Vance-Led U.S. Delegation Heading to Pakistan for Saturday Talks with Iran": "vance-led-us-delegation-heading-to-pakistan-for-saturday-talks-with-iran",
  "Venezuela Sanctions Relief Under Review After Election Delays": "venezuela-sanctions-relief-under-review-after-election-delays",
  "Venezuela Sanctions Relief Under Review as Election Promises Stall": "venezuela-sanctions-relief-under-review-as-election-promises-stall",
  "Venezuela Sanctions Remain in Place Amid Election Concerns": "venezuela-sanctions-remain-in-place-amid-election-concerns",
  "Venezuela Sanctions Review": "venezuela-sanctions-review",
  "Vestas Unveils 17 MW Offshore Turbine, World's Most Powerful": "vestas-unveils-17-mw-offshore-turbine-worlds-most-powerful",
  "Vineyard Wind Achieves Full 800 MW Output Off Massachusetts Coast": "vineyard-wind-achieves-full-800-mw-output-off-massachusetts-coast",
  "WTI Crude Climbs Past $71 as U.S. Inventories Post Sharp Drawdown": "wti-crude-climbs-past-71-as-us-inventories-post-sharp-drawdown",
  "WTI Crude Climbs Past 71 on U.S. Inventory Drawdown": "wti-crude-climbs-past-71-on-us-inventory-drawdown",
  "WTI Crude Settles at $94.41 \u2014 Biggest Single-Day Drop Since April 2020": "wti-crude-settles-at-9441-biggest-single-day-drop-since-april-2020",
  "WTI Crude Surges Past $71 on Tighter U.S. Inventory Data": "wti-crude-surges-past-71-on-tighter-us-inventory-data",
  "WTI Futures Curve Flips to Backwardation Through December 2026": "wti-futures-curve-flips-to-backwardation-through-december-2026",
  "WTI Jumps 3.7% to $94.62 on Surprise 9.13 Million Barrel U.S. Inventory Draw": "wti-jumps-37-to-9462-on-surprise-913-million-barrel-us-inventory-draw",
  "WTI Up 3.7% on Inventory Shock": "wti-up-37-on-inventory-shock",
  "WTI vs Brent Crude Oil Key Differences Explained": "wti-vs-brent-crude-oil-key-differences-explained",
  "WTI vs Brent: What's the Difference and Why It Matters": "wti-vs-brent-difference-why-it-matters",
  "What Happens If the Strait of Hormuz Closes?": "what-happens-if-strait-of-hormuz-closes",
  "What Is Brent Crude Oil and Why Does It Matter": "what-is-brent-crude-oil-and-why-does-it-matter",
  "What Is OPEC+ and How Does It Affect Oil Prices?": "what-is-opec-plus-how-it-affects-oil-prices",
  "What Is the Rig Count and Why Does It Matter for Oil Prices": "what-is-the-rig-count-and-why-does-it-matter-for-oil-prices",
  "What's the Oil Price Per Barrel Today? WTI & Brent Explained": "oil-price-per-barrel-today-wti-brent-explained",
  "Why Are Gas Prices Different in Every State?": "why-are-gas-prices-different-in-every-state",
  "Why Are Gas Prices So High What Drives Pump Prices in 2026": "why-are-gas-prices-so-high-what-drives-pump-prices-in-2026",
  "Why Do Oil Prices Change Every Day?": "why-do-oil-prices-change-every-day",
  "Why European Gas Storage Levels Matter More Than Ever": "why-european-gas-storage-levels-matter-more-than-ever",
  "Why Fewer Rigs Are Producing More Oil Than Ever": "why-fewer-rigs-are-producing-more-oil-than-ever",
  "Trump Extends Iran Ceasefire Indefinitely, Citing 'Seriously Fractured' Iranian Government": "trump-extends-iran-ceasefire-indefinitely-citing-fractured-iranian-government",
  "Trump Extends Iran Ceasefire Indefinitely, Citing 'Seriously Fractured' Government": "trump-extends-iran-ceasefire-indefinitely-citing-fractured-iranian-government",
  "Trump Extends Ceasefire Indefinitely, Citing 'Fractured' Iran": "trump-extends-iran-ceasefire-indefinitely-citing-fractured-iranian-government",
  "Trump Extends Iran Ceasefire Indefinitely on Truth Social": "trump-extends-iran-ceasefire-indefinitely-citing-fractured-iranian-government",
  "Brent Spikes Above $100 Intraday Before Retreating on Ceasefire Extension News": "brent-touches-101-intraday-before-retreating-on-ceasefire-extension",
  "Brent Touches $101 Intraday Before Retreating on Ceasefire Extension": "brent-touches-101-intraday-before-retreating-on-ceasefire-extension",
  "Brent Touches $101 Intraday Before Retreating on Extension News": "brent-touches-101-intraday-before-retreating-on-ceasefire-extension",
  "WTI Settles +3% at $92.13, Brent +3% at $98.48 on Peace Talk Uncertainty": "brent-touches-101-intraday-before-retreating-on-ceasefire-extension",
  "U.S. Naval Blockade of Iranian Ports Remains in Place Despite Ceasefire Extension": "us-naval-blockade-of-iranian-ports-remains-in-place-despite-ceasefire-extension",
  "U.S. Navy Blockade Has Turned Back 28 Ships Since Beginning": "us-naval-blockade-of-iranian-ports-remains-in-place-despite-ceasefire-extension",
  "Strait of Hormuz Remains Functionally Closed Despite Extension": "us-naval-blockade-of-iranian-ports-remains-in-place-despite-ceasefire-extension",
  "Vance's Islamabad Trip Put on Hold as Iran Fails to Confirm Delegation": "vances-islamabad-trip-put-on-hold-as-iran-fails-to-confirm-delegation",
  "Vance Holds at White House as Iran Delays Delegation Confirmation": "vances-islamabad-trip-put-on-hold-as-iran-fails-to-confirm-delegation",
  "Iran Still Hasn't Confirmed Delegation for Islamabad Talks": "vances-islamabad-trip-put-on-hold-as-iran-fails-to-confirm-delegation",
  "Hezbollah Fires Rockets at Israeli Troops in Southern Lebanon, Violating Ceasefire": "hezbollah-fires-rockets-at-israeli-troops-in-southern-lebanon-violating-ceasefire",
  "Hezbollah Fires Rockets at Israeli Troops in Southern Lebanon": "hezbollah-fires-rockets-at-israeli-troops-in-southern-lebanon-violating-ceasefire",
  "Hezbollah Rocket Fire Breaches 10-Day Ceasefire with Israel": "hezbollah-fires-rockets-at-israeli-troops-in-southern-lebanon-violating-ceasefire",
  "Iran's IRGC Threatens to Target Oil Facilities in Neighboring Countries Hosting U.S. Attacks": "irgc-threatens-to-target-oil-facilities-in-neighboring-countries-hosting-us-attacks",
  "IRGC Threatens to Target Oil Facilities in Neighboring Countries Hosting U.S. Attacks": "irgc-threatens-to-target-oil-facilities-in-neighboring-countries-hosting-us-attacks",
  "IRGC Threatens Oil Facilities in Neighboring Countries": "irgc-threatens-to-target-oil-facilities-in-neighboring-countries-hosting-us-attacks",
  "IRGC Threatens Oil Facilities in Neighboring Host Countries": "irgc-threatens-to-target-oil-facilities-in-neighboring-countries-hosting-us-attacks",
  "Iran FM Araghchi Calls U.S. Naval Blockade 'An Act of War' and Ceasefire Violation": "iran-fm-araghchi-calls-us-naval-blockade-an-act-of-war-and-ceasefire-violation",
  "Energy Stocks Mixed as Ceasefire Extension Eases but Blockade Stays": "energy-stocks-mixed-as-ceasefire-extension-eases-but-blockade-stays",
  "Maersk, Hapag-Lloyd Maintain Hormuz Transit Suspension Amid Continued Uncertainty": "maersk-hapag-lloyd-maintain-hormuz-transit-suspension-amid-continued-uncertainty",
  "Saudi Aramco East-West Pipeline Continues at Full Capacity Through Blockade": "saudi-aramco-east-west-pipeline-continues-at-full-capacity-through-blockade",
  "Cheniere Energy, Venture Global Ride LNG Premium as Qatar Flows Still Disrupted": "cheniere-energy-venture-global-ride-lng-premium-as-qatar-flows-still-disrupted",
  "OPEC+ April Output Increase Proceeding Despite Market Volatility": "opec-april-output-increase-proceeding-despite-market-volatility",
  "U.S.-Iran Ceasefire Explained: Timeline, Terms, and Extension": "us-iran-ceasefire-explained-timeline-terms-and-extension",

  // April 22-26, 2026 stories
  "Trump Orders Navy to 'Shoot and Kill' Iranian Mine-Laying Vessels in Strait": "trump-orders-navy-shoot-and-kill-iranian-mine-laying-vessels-in-strait",
  "Trump Orders Navy to 'Shoot and Kill' Iranian Boats Laying Mines in Hormuz": "trump-orders-navy-shoot-and-kill-iranian-mine-laying-vessels-in-strait",
  "Trump Escalates: 'Shoot and Kill' Order Against Iranian Mine-Laying Boats": "trump-orders-navy-shoot-and-kill-iranian-mine-laying-vessels-in-strait",
  "WTI Surges 13% on Week as Hormuz Stays Closed and Talks Stall": "wti-surges-13-percent-on-week-as-hormuz-stays-closed-and-talks-stall",
  "WTI Posts 13% Weekly Gain on Stalled Diplomacy and Hormuz Closure": "wti-surges-13-percent-on-week-as-hormuz-stays-closed-and-talks-stall",
  "Brent Up 18% on Week as Iran Talks Deadlock, Hormuz Remains Shut": "wti-surges-13-percent-on-week-as-hormuz-stays-closed-and-talks-stall",
  "Crude Oil Posts Biggest Weekly Gain Since March on Iran Standoff": "wti-surges-13-percent-on-week-as-hormuz-stays-closed-and-talks-stall",
  "Trump Cancels Witkoff-Kushner Pakistan Trip as Iran Talks Stall": "trump-cancels-witkoff-kushner-pakistan-trip-as-iran-talks-stall",
  "U.S. Envoys' Pakistan Trip Cancelled as Talks With Iran Break Down Again": "trump-cancels-witkoff-kushner-pakistan-trip-as-iran-talks-stall",
  "Trump Halts Talks: Witkoff and Kushner Trip to Islamabad Cancelled": "trump-cancels-witkoff-kushner-pakistan-trip-as-iran-talks-stall",
  "Araghchi Leaves Pakistan Without Meeting U.S. Officials as Talks Collapse": "araghchi-leaves-pakistan-without-meeting-us-officials-as-talks-collapse",
  "Iran's FM Araghchi Departs Islamabad Without U.S. Meeting": "araghchi-leaves-pakistan-without-meeting-us-officials-as-talks-collapse",
  "Araghchi Returns to Tehran After Talks With Pakistani Mediators Only": "araghchi-leaves-pakistan-without-meeting-us-officials-as-talks-collapse",
  "Israeli Strikes Kill Lebanese Journalist Amal Khalil During Extended Ceasefire": "israeli-strikes-kill-lebanese-journalist-amal-khalil-during-extended-ceasefire",
  "Lebanese Journalist Killed in Israeli Strike, Heavy Bombing Continues Despite Truce": "israeli-strikes-kill-lebanese-journalist-amal-khalil-during-extended-ceasefire",
  "Israeli Strikes on Lebanon Kill 6 Including Journalist as Ceasefire Strains": "israeli-strikes-kill-lebanese-journalist-amal-khalil-during-extended-ceasefire",
  "U.S. Boards Supertanker Carrying Iranian Oil in Indian Ocean": "us-boards-supertanker-carrying-iranian-oil-in-indian-ocean",
  "U.S. Forces Board Iranian-Oil Supertanker in Indian Ocean Interdiction": "us-boards-supertanker-carrying-iranian-oil-in-indian-ocean",
  "Sanctioned Tanker Boarded as U.S. Extends Iran Interdiction Globally": "us-boards-supertanker-carrying-iranian-oil-in-indian-ocean",

  // Additional variant phrasings used in MARKET_DRIVERS / GEO_ITEMS
  "WTI Up 13% on Week, Brent Up 18% on Hormuz Closure and Stalled Talks": "wti-surges-13-percent-on-week-as-hormuz-stays-closed-and-talks-stall",
  "WTI Up 13% on Week, Brent Up 18% — Biggest Gains Since Early March": "wti-surges-13-percent-on-week-as-hormuz-stays-closed-and-talks-stall",
  "Trump Orders Navy to 'Shoot and Kill' Iranian Mine-Laying Vessels": "trump-orders-navy-shoot-and-kill-iranian-mine-laying-vessels-in-strait",
  "Israeli Strikes Kill 6 Including Lebanese Journalist Despite Ceasefire": "israeli-strikes-kill-lebanese-journalist-amal-khalil-during-extended-ceasefire",
  "Israeli Strikes Kill 6 in South Lebanon Despite Extended Ceasefire": "israeli-strikes-kill-lebanese-journalist-amal-khalil-during-extended-ceasefire",
  "Strait Remains Closed; Iran Lost Track of Mines It Planted": "trump-orders-navy-shoot-and-kill-iranian-mine-laying-vessels-in-strait",
  "Pakistan Continues Back-Channel Mediation as Direct Talks Fail": "araghchi-leaves-pakistan-without-meeting-us-officials-as-talks-collapse",
  "Civilian-IRGC Split in Tehran Deepens; FM Civilian Track vs. Hard-Line Posture": "trump-extends-iran-ceasefire-indefinitely-citing-fractured-iranian-government",
  "ExxonMobil Q1 Earnings Preview: Hormuz Disruption Hits Trading Timing": "energy-stocks-mixed-as-ceasefire-extension-eases-but-blockade-stays",

  // ─── April 27-28, 2026 ────────────────────────────────────────────────
  "Iran Proposes Hormuz Reopening if U.S. Lifts Naval Blockade": "iran-proposes-hormuz-reopening-if-us-lifts-naval-blockade",
  "Iran Submits Formal Proposal: Reopen Hormuz, Postpone Nuclear Talks": "iran-proposes-hormuz-reopening-if-us-lifts-naval-blockade",
  "Tehran Offers Hormuz-for-Blockade Deal as Trump Weighs Response": "iran-proposes-hormuz-reopening-if-us-lifts-naval-blockade",
  "Iran's New Proposal: Hormuz for Blockade Lift, Nuclear Talks Deferred": "iran-proposes-hormuz-reopening-if-us-lifts-naval-blockade",
  "Iran's Hormuz Proposal: Reopen Strait, Postpone Nuclear Talks": "iran-proposes-hormuz-reopening-if-us-lifts-naval-blockade",

  "WTI Tops $100, Brent $111 on Iran Hormuz Proposal Uncertainty": "wti-tops-100-brent-111-on-iran-hormuz-proposal-uncertainty",
  "Crude Rallies 7th Straight Session as Markets Weigh Iran Offer": "wti-tops-100-brent-111-on-iran-hormuz-proposal-uncertainty",
  "WTI Settles at $99.93, Brent at $111.26 on Tuesday Surge": "wti-tops-100-brent-111-on-iran-hormuz-proposal-uncertainty",
  "Oil Prices Surge Nearly 4% as Trump Weighs Iran's Hormuz Deal": "wti-tops-100-brent-111-on-iran-hormuz-proposal-uncertainty",
  "Brent Crosses $111 Tuesday on Trump's Skepticism Over Iran Plan": "wti-tops-100-brent-111-on-iran-hormuz-proposal-uncertainty",
  "WTI Tops $100, Brent $111 as Markets Weigh Hormuz Proposal": "wti-tops-100-brent-111-on-iran-hormuz-proposal-uncertainty",

  "Trump Says Iran in 'State of Collapse' as Hormuz Standoff Drags Into Ninth Week": "trump-says-iran-in-state-of-collapse-as-hormuz-standoff-drags-into-ninth-week",
  "Trump: Iran 'Informed Us' It Is in State of Collapse": "trump-says-iran-in-state-of-collapse-as-hormuz-standoff-drags-into-ninth-week",
  "President Posts on Iran's 'Collapse' as Hormuz Negotiations Continue": "trump-says-iran-in-state-of-collapse-as-hormuz-standoff-drags-into-ninth-week",

  "U.S. Gas Average Hits $4.14, Highest in Nearly Four Years": "us-gas-average-hits-414-highest-in-nearly-four-years",
  "AAA: National Gas Price Climbs to $4.14 as Crude Tops $100": "us-gas-average-hits-414-highest-in-nearly-four-years",
  "Pump Prices Hit Multi-Year High as Hormuz Standoff Persists": "us-gas-average-hits-414-highest-in-nearly-four-years",
  "U.S. Retail Gasoline at $4.14, Up 11 Cents in a Week on Crude Surge": "us-gas-average-hits-414-highest-in-nearly-four-years",
  "U.S. Gas Average Climbs to $4.14, Highest Since 2022": "us-gas-average-hits-414-highest-in-nearly-four-years",

  // Exact GEO_ITEMS title strings
  "Strait of Hormuz Remains Functionally Closed in Ninth Week": "iran-proposes-hormuz-reopening-if-us-lifts-naval-blockade",
  "Trump Says Iran in 'State of Collapse' as Negotiations Continue": "trump-says-iran-in-state-of-collapse-as-hormuz-standoff-drags-into-ninth-week",
  "WTI Tops $100, Brent $111 — Seventh Consecutive Session of Gains": "wti-tops-100-brent-111-on-iran-hormuz-proposal-uncertainty"

};

function slugifyTitle(title) {
  return title.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 80);
}

// articleUrl() — returns 'articles/<slug>.html' for known titles,
// or falls back to slugify. PRESERVED AS-IS for backward compatibility
// with 26+ call sites across the site.
//
// Path A Guard B: callers that render lists (map-based card rendering)
// should filter their arrays via knownArticles() first to eliminate
// dangling references before they become <a href="..."> with bad URLs.
function articleUrl(title) {
  if (typeof ARTICLE_SLUGS !== 'undefined' && ARTICLE_SLUGS[title]) {
    return 'articles/' + ARTICLE_SLUGS[title] + '.html';
  }
  return 'articles/' + slugifyTitle(title) + '.html';
}

function categoryArticleUrl(title) {
  return '../' + articleUrl(title);
}

// Path A Guard B — predicate: is this title explicitly mapped?
// Use in Array.filter() to drop unknown titles from render loops.
function isKnownArticle(title) {
  return typeof ARTICLE_SLUGS !== 'undefined' && ARTICLE_SLUGS.hasOwnProperty(title);
}

// Path A Guard B — helper: filter a list of article objects to only
// those that will produce valid URLs. Use like:
//   .map(...)  → .filter(knownArticleFilter)  → ...
//
// Works whether the element is { title } or a bare string title.
function knownArticleFilter(item) {
  if (!item) return false;
  var title = (typeof item === 'string') ? item : item.title;
  return isKnownArticle(title);
}
